spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config: 
      server:
        git:
          uri: https://github.com/liucaijin/Config-Repo
      label: master
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
   instance:
      hostname: config-server
      instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
server:
  port: 8888
logging:
  config: classpath:logback-spring.xml